In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("D:\Study\Codeneara\Project\Finace_Project\Loan_Approval_Rrisk_Pattern_Analysis\Data.CSV")

df.head()

,customer_id,age,gender,education,employment_type,employment_length,annual_income,existing_emi,debt_to_income_ratio,cibil_score,...,city,area_type,loan_approval_time_days,document_verification_status,loan_approval_status,rejection_reason,EMI,EMI_to_Income_Ratio,risk_rule,Loan_to_Income_Ratio
0,1,40,Male,Graduate,Salaried,21,737179,6113,0.20,654,...,Bathinda,Urban,3,Processing,Approved,NaN,5924.93,0.10,Low,0.23
1,2,47,Male,Graduate,Salaried,9,640639,6780,0.15,518,...,Haldia,Urban,5,Done,Rejected,Low Income,1241.85,0.02,Low,0.10
2,3,43,Male,Graduate,Salaried,23,666628,6926,0.16,462,...,Alwar,Urban,13,Processing,Approved,NaN,2188.67,0.04,Low,0.25
3,4,28,Female,Graduate,Self-employed,23,1143020,17211,0.23,492,...,Jorhat,Urban,3,Done,Rejected,High Existing EMI,4961.03,0.05,Low,0.21
4,5,51,Male,Graduate,Salaried,30,366810,15839,0.55,507,...,Aurangabad,Rural,1,Done,Approved,NaN,924.23,0.03,Low,0.14

In [5]:
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 32 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   3000 non-null   int64
 1   age                           3000 non-null   int64
 2   gender                        3000 non-null   object
 3   education                     3000 non-null   object
 4   employment_type               3000 non-null   object
 5   employment_length             3000 non-null   int64
 6   annual_income                 3000 non-null   int64
 7   existing_emi                  3000 non-null   int64
 8   debt_to_income_ratio          3000 non-null   float64
 9   cibil_score                   3000 non-null   int64
 10  credit_utilization_ratio      3000 non-null   float64
 11  previous_default              3000 non-null   object
 12  loan_amount                   3000 non-null   int64
 13  loan_type                     3000 non-null   object
 14  loan_purpose                  3000 non-null   object
 15  loan_tenure_years             3000 non-null   int64
 16  interest_rate                 3000 non-null   float64
 17  risk_category                 3000 non-null   object
 18  lender_type                   3000 non-null   object
 19  loan_processing_fee_percent   3000 non-null   float64
 20  application_channel           3000 non-null   object
 21  state                         3000 non-null   object
 22  city                          3000 non-null   object
 23  area_type                     3000 non-null   object
 24  loan_approval_time_days       3000 non-null   int64
 25  document_verification_status  3000 non-null   object
 26  loan_approval_status          3000 non-null   object
 27  rejection_reason              451 non-null    object
 28  EMI                           3000 non-null   float64
 29  EMI_to_Income_Ratio           3000 non-null   float64
 30   risk_rule                    3000 non-null   object
 31  Loan_to_Income_Ratio          3000 non-null   float64
dtypes: float64(7), int64(9), object(16)
memory usage: 750.1+ KB

customer_id                        0
age                                0
gender                             0
education                          0
employment_type                    0
employment_length                  0
annual_income                      0
existing_emi                       0
debt_to_income_ratio               0
cibil_score                        0
credit_utilization_ratio           0
previous_default                   0
loan_amount                        0
loan_type                          0
loan_purpose                       0
loan_tenure_years                  0
interest_rate                      0
risk_category                      0
lender_type                        0
loan_processing_fee_percent        0
application_channel                0
state                              0
city                               0
area_type                          0
loan_approval_time_days            0
document_verification_status       0
loan_approval_status               0
rejection_reason                2549
EMI                                0
EMI_to_Income_Ratio                0
 risk_rule                         0
Loan_to_Income_Ratio               0
dtype: int64

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df['rejection_reason'] = df['rejection_reason'].fillna("Not Rejected")

In [8]:
# Loan Approval Rate

df['loan_approval_status'].value_counts(normalize=True) * 100

loan_approval_status
Approved    62.166667
Pending     22.800000
Rejected    15.033333
Name: proportion, dtype: float64

In [9]:
# CIBIL Score vs Loan Approval

pd.crosstab(df['risk_category'], df['loan_approval_status'])

loan_approval_status  Approved  Pending  Rejected
risk_category
High                       704      362       324
Low                        608       63        63
Medium                     553      259        64

In [10]:
# Previous Default vs Approval

pd.crosstab(df['previous_default'], df['loan_approval_status'])

loan_approval_status  Approved  Pending  Rejected
previous_default
No                        1723      626       421
Yes                        142       58        30

In [11]:
# Debt-to-Income Ratio vs Approval

df.groupby('loan_approval_status')['debt_to_income_ratio'].mean()

loan_approval_status
Approved    0.415276
Pending     0.402646
Rejected    0.429889
Name: debt_to_income_ratio, dtype: float64

In [12]:
# EMI-to-Income Ratio vs Approval

df.groupby('loan_approval_status')['EMI_to_Income_Ratio'].mean()

loan_approval_status
Approved    0.188654
Pending     0.186404
Rejected    0.197051
Name: EMI_to_Income_Ratio, dtype: float64

In [13]:
# Income vs Loan Amount

df[['annual_income', 'loan_amount']].corr()

               annual_income  loan_amount
annual_income       1.000000     0.283865
loan_amount         0.283865     1.000000

In [14]:
# Risk Category Distribution

df['risk_category'].value_counts()

risk_category
High      1390
Medium     876
Low        734
Name: count, dtype: int64

In [15]:
# Rejection Reasons

df[df['loan_approval_status'] == 'Rejected']['rejection_reason'].value_counts()

rejection_reason
Low Income                        83
Low CIBIL Score                   83
High Existing EMI                 80
Previous Loan Default             80
High Loan Amount Request          66
Insufficient Employment Length    59
Name: count, dtype: int64

In [16]:
# bank behavior differences

pd.crosstab(df['lender_type'], df['loan_approval_status'])

loan_approval_status  Approved  Pending  Rejected
lender_type
Finance Company            622      216       153
Government Bank            620      223       142
Private Bank               623      245       156

In [17]:
df.to_csv("final_loan_data.csv", index=False)